main: com.cavetale.memberlist.MemberListPlugin
name: MemberList

version: 0.1
api-version: '1.21'

description: Member List Plugin
author: StarTux
website: https://cavetale.com

depend: [Core, Connect, SQL, PlayerCache]
softdepend: []

commands:

  memberlist:
    aliases: [ml]
    description: MemberList Command
    permission: memberlist.memberlist
    usage: |-
      /ml add <player>
      /ml addall - Add everyone online
      /ml nearby <radius> - List nearby players (for copying)
      /ml addnearby <radius> - Add nearby players
      /ml remove <player>
      /ml check <player>
      /ml list
      /ml reload
      /ml clear
      /ml dump - Dump to yaml

permissions:

  memberlist.memberlist:
    description: Use /memberlist
    default: op
